# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtenderSolicita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=128)),
                ('chassi', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoSocitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField()),
                ('origem', models.CharField(max_length=128)),
                ('destino', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nome_departamento', to='transporte.Departamento')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=128)),
                ('cnh', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='departamentosocitacao',
            name='funcionario',
            field=models.ManyToManyField(null=True, to='transporte.Funcionario'),
        ),
        migrations.AddField(
            model_name='atendersolicita',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='transporte.Carro'),
        ),
        migrations.AddField(
            model_name='atendersolicita',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_socilitar', to='transporte.DepartamentoSocitacao'),
        ),
        migrations.AddField(
            model_name='atendersolicita',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista', to='transporte.Motorista'),
        ),
    ]
