# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_auto_20171204_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentosocitacao',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='departamentosocitacao',
            name='funcionario',
            field=models.ManyToManyField(to='transporte.Funcionario'),
        ),
    ]
